# Generated by Django 5.1.3 on 2025-05-18 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Prompt')),
                ('negative_prompt', models.TextField(blank=True, null=True, verbose_name='Negative Prompt')),
                ('width', models.IntegerField(verbose_name='Image Width')),
                ('height', models.IntegerField(verbose_name='Image Height')),
                ('images', models.JSONField(verbose_name='Generated Images')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Generated At')),
            ],
            options={
                'verbose_name': 'Image Generation History',
                'verbose_name_plural': 'Image Generation History',
            },
        ),
        migrations.AlterModelOptions(
            name='recentsearch',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Recent Search', 'verbose_name_plural': 'Recent Searches'},
        ),
        migrations.AlterField(
            model_name='recentsearch',
            name='query',
            field=models.CharField(max_length=255, verbose_name='Search Query'),
        ),
        migrations.AlterField(
            model_name='recentsearch',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Search Time'),
        ),
        migrations.AlterField(
            model_name='recentsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
